### ISSUE TITLE
Allow simple lookup

### ISSUE THREAD

**Issue by kevinjhanna** [tonchis/fat#5]
Currently, Fat does not support simple lookups.

I would like to use Fat in a project where I don't know if keys are more than 1 level deep.

I don't know if this would be the best syntax for it ``Fat.at(hash, "foo:")`` or  ``Fat.at(hash, "foo.")``

What do you think?

This is the test case against this feature:

    test "single argument must be a namespace" do
        assert_raise(Fat::FatError) { Fat.at({"foo" => "bar"}, "foo") }
    end

**Comment by tonchis** [comment]
This is implemented in v2.0.1; [test here](https://github.com/tonchis/fat/blob/dea15312cd43885db662919ec04b76d4cb8d6bdd/test/fat_test.rb#L74-L76)
